import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ITLA Training Program (POMA)",
  description: "Generated by BootsDev-X",
  icons: "/ITLA.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={` google-sans bg-black antialiased`}>{children}</body>
    </html>
  );
}
